// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=mocks_test.go -package=schedule_test
//

// Package schedule_test is a generated GoMock package.
package schedule_test

import (
	context "context"
	reflect "reflect"

	domain "github.com/iamroockie/pulsewatch/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockClaimer is a mock of Claimer interface.
type MockClaimer struct {
	ctrl     *gomock.Controller
	recorder *MockClaimerMockRecorder
	isgomock struct{}
}

// MockClaimerMockRecorder is the mock recorder for MockClaimer.
type MockClaimerMockRecorder struct {
	mock *MockClaimer
}

// NewMockClaimer creates a new mock instance.
func NewMockClaimer(ctrl *gomock.Controller) *MockClaimer {
	mock := &MockClaimer{ctrl: ctrl}
	mock.recorder = &MockClaimerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClaimer) EXPECT() *MockClaimerMockRecorder {
	return m.recorder
}

// ClaimDue mocks base method.
func (m *MockClaimer) ClaimDue(ctx context.Context, limit int) ([]domain.Claim, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClaimDue", ctx, limit)
	ret0, _ := ret[0].([]domain.Claim)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClaimDue indicates an expected call of ClaimDue.
func (mr *MockClaimerMockRecorder) ClaimDue(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClaimDue", reflect.TypeOf((*MockClaimer)(nil).ClaimDue), ctx, limit)
}

// MockWorkers is a mock of Workers interface.
type MockWorkers struct {
	ctrl     *gomock.Controller
	recorder *MockWorkersMockRecorder
	isgomock struct{}
}

// MockWorkersMockRecorder is the mock recorder for MockWorkers.
type MockWorkersMockRecorder struct {
	mock *MockWorkers
}

// NewMockWorkers creates a new mock instance.
func NewMockWorkers(ctrl *gomock.Controller) *MockWorkers {
	mock := &MockWorkers{ctrl: ctrl}
	mock.recorder = &MockWorkersMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkers) EXPECT() *MockWorkersMockRecorder {
	return m.recorder
}

// Free mocks base method.
func (m *MockWorkers) Free() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Free")
	ret0, _ := ret[0].(int)
	return ret0
}

// Free indicates an expected call of Free.
func (mr *MockWorkersMockRecorder) Free() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Free", reflect.TypeOf((*MockWorkers)(nil).Free))
}

// Freed mocks base method.
func (m *MockWorkers) Freed() <-chan struct{} {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Freed")
	ret0, _ := ret[0].(<-chan struct{})
	return ret0
}

// Freed indicates an expected call of Freed.
func (mr *MockWorkersMockRecorder) Freed() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Freed", reflect.TypeOf((*MockWorkers)(nil).Freed))
}

// Go mocks base method.
func (m *MockWorkers) Go(c domain.Claim) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Go", c)
}

// Go indicates an expected call of Go.
func (mr *MockWorkersMockRecorder) Go(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Go", reflect.TypeOf((*MockWorkers)(nil).Go), c)
}
