// Code generated by MockGen. DO NOT EDIT.
// Source: monitor.go
//
// Generated by this command:
//
//	mockgen -source=monitor.go -destination=mock_repository_test.go -package=service_test
//

// Package service_test is a generated GoMock package.
package service_test

import (
	context "context"
	reflect "reflect"
	uuid "uuid"

	domain "github.com/iamroockie/pulsewatch/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockMonitorRepository is a mock of MonitorRepository interface.
type MockMonitorRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMonitorRepositoryMockRecorder
	isgomock struct{}
}

// MockMonitorRepositoryMockRecorder is the mock recorder for MockMonitorRepository.
type MockMonitorRepositoryMockRecorder struct {
	mock *MockMonitorRepository
}

// NewMockMonitorRepository creates a new mock instance.
func NewMockMonitorRepository(ctrl *gomock.Controller) *MockMonitorRepository {
	mock := &MockMonitorRepository{ctrl: ctrl}
	mock.recorder = &MockMonitorRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMonitorRepository) EXPECT() *MockMonitorRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m_2 *MockMonitorRepository) Create(ctx context.Context, m *domain.Monitor) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Create", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockMonitorRepositoryMockRecorder) Create(ctx, m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockMonitorRepository)(nil).Create), ctx, m)
}

// Delete mocks base method.
func (m *MockMonitorRepository) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockMonitorRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockMonitorRepository)(nil).Delete), ctx, id)
}

// Get mocks base method.
func (m *MockMonitorRepository) Get(ctx context.Context, id uuid.UUID) (*domain.Monitor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*domain.Monitor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockMonitorRepositoryMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockMonitorRepository)(nil).Get), ctx, id)
}

// List mocks base method.
func (m *MockMonitorRepository) List(ctx context.Context, after uuid.UUID, limit int) ([]*domain.Monitor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, after, limit)
	ret0, _ := ret[0].([]*domain.Monitor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockMonitorRepositoryMockRecorder) List(ctx, after, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockMonitorRepository)(nil).List), ctx, after, limit)
}

// Update mocks base method.
func (m *MockMonitorRepository) Update(ctx context.Context, id uuid.UUID, fn func(*domain.Monitor) error) (*domain.Monitor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, fn)
	ret0, _ := ret[0].(*domain.Monitor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockMonitorRepositoryMockRecorder) Update(ctx, id, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockMonitorRepository)(nil).Update), ctx, id, fn)
}
