// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=mocks_test.go -package=service_test
//

// Package service_test is a generated GoMock package.
package service_test

import (
	context "context"
	reflect "reflect"
	time "time"
	uuid "uuid"

	domain "github.com/iamroockie/pulsewatch/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockCheckRepository is a mock of CheckRepository interface.
type MockCheckRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCheckRepositoryMockRecorder
	isgomock struct{}
}

// MockCheckRepositoryMockRecorder is the mock recorder for MockCheckRepository.
type MockCheckRepositoryMockRecorder struct {
	mock *MockCheckRepository
}

// NewMockCheckRepository creates a new mock instance.
func NewMockCheckRepository(ctrl *gomock.Controller) *MockCheckRepository {
	mock := &MockCheckRepository{ctrl: ctrl}
	mock.recorder = &MockCheckRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCheckRepository) EXPECT() *MockCheckRepositoryMockRecorder {
	return m.recorder
}

// ClaimDue mocks base method.
func (m *MockCheckRepository) ClaimDue(ctx context.Context, now time.Time, retryDelay, margin time.Duration, limit int) ([]domain.Claim, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClaimDue", ctx, now, retryDelay, margin, limit)
	ret0, _ := ret[0].([]domain.Claim)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClaimDue indicates an expected call of ClaimDue.
func (mr *MockCheckRepositoryMockRecorder) ClaimDue(ctx, now, retryDelay, margin, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClaimDue", reflect.TypeOf((*MockCheckRepository)(nil).ClaimDue), ctx, now, retryDelay, margin, limit)
}

// CountDue mocks base method.
func (m *MockCheckRepository) CountDue(ctx context.Context, now time.Time) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountDue", ctx, now)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountDue indicates an expected call of CountDue.
func (mr *MockCheckRepositoryMockRecorder) CountDue(ctx, now any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountDue", reflect.TypeOf((*MockCheckRepository)(nil).CountDue), ctx, now)
}

// DeleteBefore mocks base method.
func (m *MockCheckRepository) DeleteBefore(ctx context.Context, cutoff time.Time) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBefore", ctx, cutoff)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteBefore indicates an expected call of DeleteBefore.
func (mr *MockCheckRepositoryMockRecorder) DeleteBefore(ctx, cutoff any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBefore", reflect.TypeOf((*MockCheckRepository)(nil).DeleteBefore), ctx, cutoff)
}

// Record mocks base method.
func (m *MockCheckRepository) Record(ctx context.Context, check *domain.Check, until time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Record", ctx, check, until)
	ret0, _ := ret[0].(error)
	return ret0
}

// Record indicates an expected call of Record.
func (mr *MockCheckRepositoryMockRecorder) Record(ctx, check, until any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Record", reflect.TypeOf((*MockCheckRepository)(nil).Record), ctx, check, until)
}

// Release mocks base method.
func (m *MockCheckRepository) Release(ctx context.Context, id uuid.UUID, until, retryAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Release", ctx, id, until, retryAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// Release indicates an expected call of Release.
func (mr *MockCheckRepositoryMockRecorder) Release(ctx, id, until, retryAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Release", reflect.TypeOf((*MockCheckRepository)(nil).Release), ctx, id, until, retryAt)
}

// MockChecker is a mock of Checker interface.
type MockChecker struct {
	ctrl     *gomock.Controller
	recorder *MockCheckerMockRecorder
	isgomock struct{}
}

// MockCheckerMockRecorder is the mock recorder for MockChecker.
type MockCheckerMockRecorder struct {
	mock *MockChecker
}

// NewMockChecker creates a new mock instance.
func NewMockChecker(ctrl *gomock.Controller) *MockChecker {
	mock := &MockChecker{ctrl: ctrl}
	mock.recorder = &MockCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChecker) EXPECT() *MockCheckerMockRecorder {
	return m.recorder
}

// Check mocks base method.
func (m *MockChecker) Check(ctx context.Context, s domain.CheckSettings) (domain.CheckResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Check", ctx, s)
	ret0, _ := ret[0].(domain.CheckResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Check indicates an expected call of Check.
func (mr *MockCheckerMockRecorder) Check(ctx, s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Check", reflect.TypeOf((*MockChecker)(nil).Check), ctx, s)
}

// MockHistoryRepository is a mock of HistoryRepository interface.
type MockHistoryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockHistoryRepositoryMockRecorder
	isgomock struct{}
}

// MockHistoryRepositoryMockRecorder is the mock recorder for MockHistoryRepository.
type MockHistoryRepositoryMockRecorder struct {
	mock *MockHistoryRepository
}

// NewMockHistoryRepository creates a new mock instance.
func NewMockHistoryRepository(ctrl *gomock.Controller) *MockHistoryRepository {
	mock := &MockHistoryRepository{ctrl: ctrl}
	mock.recorder = &MockHistoryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHistoryRepository) EXPECT() *MockHistoryRepositoryMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockHistoryRepository) List(ctx context.Context, monitorID uuid.UUID, before time.Time, limit int) ([]*domain.Check, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, monitorID, before, limit)
	ret0, _ := ret[0].([]*domain.Check)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockHistoryRepositoryMockRecorder) List(ctx, monitorID, before, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockHistoryRepository)(nil).List), ctx, monitorID, before, limit)
}

// Uptime mocks base method.
func (m *MockHistoryRepository) Uptime(ctx context.Context, monitorID uuid.UUID, now time.Time) (domain.UptimeReport, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Uptime", ctx, monitorID, now)
	ret0, _ := ret[0].(domain.UptimeReport)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Uptime indicates an expected call of Uptime.
func (mr *MockHistoryRepositoryMockRecorder) Uptime(ctx, monitorID, now any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Uptime", reflect.TypeOf((*MockHistoryRepository)(nil).Uptime), ctx, monitorID, now)
}

// MockHostLimiter is a mock of HostLimiter interface.
type MockHostLimiter struct {
	ctrl     *gomock.Controller
	recorder *MockHostLimiterMockRecorder
	isgomock struct{}
}

// MockHostLimiterMockRecorder is the mock recorder for MockHostLimiter.
type MockHostLimiterMockRecorder struct {
	mock *MockHostLimiter
}

// NewMockHostLimiter creates a new mock instance.
func NewMockHostLimiter(ctrl *gomock.Controller) *MockHostLimiter {
	mock := &MockHostLimiter{ctrl: ctrl}
	mock.recorder = &MockHostLimiterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHostLimiter) EXPECT() *MockHostLimiterMockRecorder {
	return m.recorder
}

// Acquire mocks base method.
func (m *MockHostLimiter) Acquire(ctx context.Context, c domain.Claim, now time.Time) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Acquire", ctx, c, now)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Acquire indicates an expected call of Acquire.
func (mr *MockHostLimiterMockRecorder) Acquire(ctx, c, now any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Acquire", reflect.TypeOf((*MockHostLimiter)(nil).Acquire), ctx, c, now)
}

// Release mocks base method.
func (m *MockHostLimiter) Release(ctx context.Context, c domain.Claim) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Release", ctx, c)
	ret0, _ := ret[0].(error)
	return ret0
}

// Release indicates an expected call of Release.
func (mr *MockHostLimiterMockRecorder) Release(ctx, c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Release", reflect.TypeOf((*MockHostLimiter)(nil).Release), ctx, c)
}

// MockMonitorRepository is a mock of MonitorRepository interface.
type MockMonitorRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMonitorRepositoryMockRecorder
	isgomock struct{}
}

// MockMonitorRepositoryMockRecorder is the mock recorder for MockMonitorRepository.
type MockMonitorRepositoryMockRecorder struct {
	mock *MockMonitorRepository
}

// NewMockMonitorRepository creates a new mock instance.
func NewMockMonitorRepository(ctrl *gomock.Controller) *MockMonitorRepository {
	mock := &MockMonitorRepository{ctrl: ctrl}
	mock.recorder = &MockMonitorRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMonitorRepository) EXPECT() *MockMonitorRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m_2 *MockMonitorRepository) Create(ctx context.Context, m *domain.Monitor) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Create", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockMonitorRepositoryMockRecorder) Create(ctx, m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockMonitorRepository)(nil).Create), ctx, m)
}

// Delete mocks base method.
func (m *MockMonitorRepository) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockMonitorRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockMonitorRepository)(nil).Delete), ctx, id)
}

// Get mocks base method.
func (m *MockMonitorRepository) Get(ctx context.Context, id uuid.UUID) (*domain.Monitor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*domain.Monitor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockMonitorRepositoryMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockMonitorRepository)(nil).Get), ctx, id)
}

// List mocks base method.
func (m *MockMonitorRepository) List(ctx context.Context, after uuid.UUID, limit int) ([]*domain.Monitor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, after, limit)
	ret0, _ := ret[0].([]*domain.Monitor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockMonitorRepositoryMockRecorder) List(ctx, after, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockMonitorRepository)(nil).List), ctx, after, limit)
}

// Update mocks base method.
func (m *MockMonitorRepository) Update(ctx context.Context, id uuid.UUID, fn func(*domain.Monitor) error) (*domain.Monitor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, fn)
	ret0, _ := ret[0].(*domain.Monitor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockMonitorRepositoryMockRecorder) Update(ctx, id, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockMonitorRepository)(nil).Update), ctx, id, fn)
}
