// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=mocks_test.go -package=rest_test
//

// Package rest_test is a generated GoMock package.
package rest_test

import (
	context "context"
	reflect "reflect"
	time "time"
	uuid "uuid"

	domain "github.com/iamroockie/pulsewatch/internal/domain"
	service "github.com/iamroockie/pulsewatch/internal/service"
	gomock "go.uber.org/mock/gomock"
)

// MockHistoryService is a mock of HistoryService interface.
type MockHistoryService struct {
	ctrl     *gomock.Controller
	recorder *MockHistoryServiceMockRecorder
	isgomock struct{}
}

// MockHistoryServiceMockRecorder is the mock recorder for MockHistoryService.
type MockHistoryServiceMockRecorder struct {
	mock *MockHistoryService
}

// NewMockHistoryService creates a new mock instance.
func NewMockHistoryService(ctrl *gomock.Controller) *MockHistoryService {
	mock := &MockHistoryService{ctrl: ctrl}
	mock.recorder = &MockHistoryServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHistoryService) EXPECT() *MockHistoryServiceMockRecorder {
	return m.recorder
}

// Checks mocks base method.
func (m *MockHistoryService) Checks(ctx context.Context, monitorID uuid.UUID, before time.Time, limit int) (service.CheckPage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Checks", ctx, monitorID, before, limit)
	ret0, _ := ret[0].(service.CheckPage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Checks indicates an expected call of Checks.
func (mr *MockHistoryServiceMockRecorder) Checks(ctx, monitorID, before, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Checks", reflect.TypeOf((*MockHistoryService)(nil).Checks), ctx, monitorID, before, limit)
}

// Uptime mocks base method.
func (m *MockHistoryService) Uptime(ctx context.Context, monitorID uuid.UUID) (domain.UptimeReport, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Uptime", ctx, monitorID)
	ret0, _ := ret[0].(domain.UptimeReport)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Uptime indicates an expected call of Uptime.
func (mr *MockHistoryServiceMockRecorder) Uptime(ctx, monitorID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Uptime", reflect.TypeOf((*MockHistoryService)(nil).Uptime), ctx, monitorID)
}

// MockMonitorService is a mock of MonitorService interface.
type MockMonitorService struct {
	ctrl     *gomock.Controller
	recorder *MockMonitorServiceMockRecorder
	isgomock struct{}
}

// MockMonitorServiceMockRecorder is the mock recorder for MockMonitorService.
type MockMonitorServiceMockRecorder struct {
	mock *MockMonitorService
}

// NewMockMonitorService creates a new mock instance.
func NewMockMonitorService(ctrl *gomock.Controller) *MockMonitorService {
	mock := &MockMonitorService{ctrl: ctrl}
	mock.recorder = &MockMonitorServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMonitorService) EXPECT() *MockMonitorServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockMonitorService) Create(ctx context.Context, settings domain.CheckSettings) (*domain.Monitor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, settings)
	ret0, _ := ret[0].(*domain.Monitor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockMonitorServiceMockRecorder) Create(ctx, settings any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockMonitorService)(nil).Create), ctx, settings)
}

// Delete mocks base method.
func (m *MockMonitorService) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockMonitorServiceMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockMonitorService)(nil).Delete), ctx, id)
}

// Get mocks base method.
func (m *MockMonitorService) Get(ctx context.Context, id uuid.UUID) (*domain.Monitor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*domain.Monitor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockMonitorServiceMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockMonitorService)(nil).Get), ctx, id)
}

// List mocks base method.
func (m *MockMonitorService) List(ctx context.Context, after uuid.UUID, limit int) (service.MonitorPage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, after, limit)
	ret0, _ := ret[0].(service.MonitorPage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockMonitorServiceMockRecorder) List(ctx, after, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockMonitorService)(nil).List), ctx, after, limit)
}

// Update mocks base method.
func (m *MockMonitorService) Update(ctx context.Context, id uuid.UUID, changes domain.MonitorChanges) (*domain.Monitor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, changes)
	ret0, _ := ret[0].(*domain.Monitor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockMonitorServiceMockRecorder) Update(ctx, id, changes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockMonitorService)(nil).Update), ctx, id, changes)
}
